name: Provision EKS Cluster

on: [push]
env:
  ECR_REPOSITORY: dso
  EKS_CLUSTER_NAME: k8s
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Set short git commit SHA
              id: commit
              uses: prompt/actions-commit-hash@v2
              
            - name: Checkout code
              uses: actions/checkout@v2.3.4

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-east-1

            - name: Install AWS CLI
              run: |
                curl "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
                unzip awscliv2.zip
                sudo ./aws/install --update

            - name: Login to Amazon ECR
              run: |
                 aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/p0x4e8u7

            - name: Build, tag, and push image to Amazon ECR
              run: |
                docker build -t dso .
                docker tag dso:latest public.ecr.aws/p0x4e8u7/dso:latest
                docker push public.ecr.aws/p0x4e8u7/dso:latest

            - name: Update kube config
              run: |
                  aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region us-east-1

            - name: Deploy to EKS
              env:
                ECR_REGISTRY: public.ecr.aws/p0x4e8u7/dso        
                IMAGE_TAG: latest
              run: |
                  kubectl apply -f deployment.yaml
               
